"""standardize_measurement_type_names_for_translations

Revision ID: 0ea77b865665
Revises: 73194f9f38be
Create Date: 2025-07-01 19:38:32.462692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea77b865665'
down_revision: Union[str, None] = '73194f9f38be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Update existing measurement type names to use translation keys
    # This ensures consistency with the new translation system

    # Define mapping from old names to new translation keys
    name_mappings = {
        'Weight': 'weight',
        'Waist': 'waist',
        'Chest': 'chest',
        'Biceps': 'bicep',
        'Bicep': 'bicep',
        'Thigh': 'thigh',
        'Hip': 'hips',
        'Hips': 'hips',
        'Neck': 'neck',
        'Body Fat %': 'body_fat',
        'Muscle Mass': 'muscle_mass',
        'Height': 'height',
        'Forearm': 'forearm',
        'Calf': 'calf',
        'Shoulders': 'shoulders'
    }

    # Update measurement type names
    for old_name, new_name in name_mappings.items():
        op.execute(f"""
            UPDATE measurement_types
            SET name = '{new_name}'
            WHERE name = '{old_name}' AND created_by_user_id IS NULL
        """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Reverse the mapping to restore original names
    name_mappings = {
        'weight': 'Weight',
        'waist': 'Waist',
        'chest': 'Chest',
        'bicep': 'Bicep',
        'thigh': 'Thigh',
        'hips': 'Hip',
        'neck': 'Neck',
        'body_fat': 'Body Fat %',
        'muscle_mass': 'Muscle Mass',
        'height': 'Height',
        'forearm': 'Forearm',
        'calf': 'Calf',
        'shoulders': 'Shoulders'
    }

    # Restore original measurement type names
    for new_name, old_name in name_mappings.items():
        op.execute(f"""
            UPDATE measurement_types
            SET name = '{old_name}'
            WHERE name = '{new_name}' AND created_by_user_id IS NULL
        """)

    # ### end Alembic commands ###
