"""Add coach-athlete relationship functionality

Revision ID: 3f851f535582
Revises: edca2b899484
Create Date: 2025-07-03 13:07:06.770689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f851f535582'
down_revision: Union[str, None] = 'edca2b899484'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_athlete_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('coach_id != athlete_id', name='check_no_self_coaching'),
    sa.ForeignKeyConstraint(['athlete_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id', 'athlete_id', name='uq_coach_athlete')
    )
    # Add user_role column with default value for existing users
    op.add_column('users', sa.Column('user_role', sa.String(length=20), nullable=True))
    # Set default value for existing users
    op.execute("UPDATE users SET user_role = 'athlete' WHERE user_role IS NULL")
    # Make column non-nullable after setting default values
    op.alter_column('users', 'user_role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    op.drop_table('coach_athlete_relationships')
    # ### end Alembic commands ###
