"""Fix unique constraint for athlete coach requests

Revision ID: 621eded719b0
Revises: 04bcd27198fe
Create Date: 2025-07-05 16:37:52.838726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '621eded719b0'
down_revision: Union[str, None] = '04bcd27198fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the old unique constraint that includes status
    op.drop_constraint('uq_coach_athlete_request', 'athlete_coach_requests', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate the old constraint
    op.create_unique_constraint(
        'uq_coach_athlete_request',
        'athlete_coach_requests',
        ['coach_id', 'athlete_id', 'status']
    )
    # ### end Alembic commands ###
