"""Add custom measurement types support

Revision ID: 9db39a53df76
Revises: 3711bdfec066
Create Date: 2025-07-01 11:26:57.304870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9db39a53df76'
down_revision: Union[str, None] = '3711bdfec066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns with default values for existing data
    op.add_column('measurement_types', sa.Column('is_custom', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('measurement_types', sa.Column('created_by_user_id', sa.Integer(), nullable=True))

    # Remove the server default after adding the column
    op.alter_column('measurement_types', 'is_custom', server_default=None)

    op.drop_constraint('measurement_types_name_key', 'measurement_types', type_='unique')
    op.create_unique_constraint('uq_measurement_type_name_user', 'measurement_types', ['name', 'created_by_user_id'])
    op.create_foreign_key(None, 'measurement_types', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'measurement_types', type_='foreignkey')
    op.drop_constraint('uq_measurement_type_name_user', 'measurement_types', type_='unique')
    op.create_unique_constraint('measurement_types_name_key', 'measurement_types', ['name'])
    op.drop_column('measurement_types', 'created_by_user_id')
    op.drop_column('measurement_types', 'is_custom')
    # ### end Alembic commands ###
